flow-control-api spec
openshift/enhancements pull request #1028
Opened 2022-02-08 04:18 UTC by pmoogi-redhat

As a cluster admin I want to be able to set a flow control policy or logging rate limiting policy : drop as if logging rate exceeds rate limits provided (bytes/sec) on selected containers, ignore by dropping entire logs from selected group of containers.

*A cluster-wide default for all containers (optional)
*A special rate for containers in named namespaces
*A special rate for containers matching a label selector
*Rates are per-container and measured in bytes/sec,  the default value -1 means no limits are applied (default behaviour), 0 - means ignore entirely that set of selected containers logs belonging to a defined group

Rates are enforced by dropping log data if it exceeds the rate. Cluster Logging Forwarder Spec applies RateLimiting policies to its input sources of logs and also its output endpoints connecting to a given persistent storage.

JIRA Reference [Epic] - https://issues.redhat.com/browse/LOG-884
JIRA Reference [Story] - https://issues.redhat.com/browse/LOG-2207

2022-02-08 04:18 UTC, pmoogi-redhat commented
@alanconway please review

2022-02-10 15:27 UTC, alanconway requested changes
Made some suggested changes, you can apply them automatically via github. Important points:
- changed input.limit to input.perContainerLimit
- changed limit.maxBytesPerSecond to input.MaxRecordsPerSecond

2022-02-10 15:28 UTC, alanconway commented
@pmoogiThis should be linked to https://issues.redhat.com/browse/LOG-1043 - that task is specifically for designing the API.
 https://issues.redhat.com/browse/LOG-2207 is about implementing it.

2022-03-09 22:10 UTC, alanconway commented
I have some updates from recent discussion to be included as soon as I get a chance to write them up.
/hold

2022-03-24 15:37 UTC, alanconway commented
/unhold
/lgtm

2022-03-24 15:37 UTC, alanconway commented
I will update in a separate PR.

2022-03-24 20:39 UTC, alanconway commented
/approved

2022-03-24 20:52 UTC, merged