[WINC] WMCO: Update container runtime details
openshift/enhancements pull request #1175
Opened 2022-07-07 21:27 UTC by mansikulkarni96

This PR updates the non-goals and design details of this enhancement document related to container runtime
management by WMCO.
6.0.0 onwards Containerd runtime is installed and managed by WMCO on the Windows nodes which it configures.

2022-07-08 00:22 UTC, Anandnatraj commented
Lets use lower case containerd throughout the doc.

2022-07-12 18:50 UTC, mansikulkarni96 commented on enhancements/windows-containers/windows-machine-config-operator.md
> +* Containerd
@Anandnatraj containerd is lower case except this one place where it has been capitalized as the first letter of the bullet point.

2022-07-15 16:45 UTC, aravindhp requested changes
Thanks for writing this up. @mansikulkarni96. Please address my comments.

2022-07-15 16:45 UTC, aravindhp commented on enhancements/windows-containers/windows-machine-config-operator.md
> -where they reference a Windows OS image which has the Docker container runtime
You again need to retain this bullet and reference the WMCO versions where we support Docker.

2022-07-15 16:45 UTC, aravindhp commented on enhancements/windows-containers/windows-machine-config-operator.md
> +* Configure containerd as the default container runtime
Again, please mention the WMCO version where this will happen. Example: WMCO 6.0.0+ etc.

2022-08-15 15:22 UTC, aravindhp commented
/remove-lifecycle stale

@mansikulkarni96 please address the comments and lets close this out.

2022-08-15 22:52 UTC, mansikulkarni96 commented on enhancements/windows-containers/windows-machine-config-operator.md
> -* Installing the container runtime in the Windows node
We were not installing docker but now we are installing containerd. Therefore it makes more sense to me to remove it from non-goals and add it to the goals now.

2022-08-15 22:53 UTC, mansikulkarni96 commented
> /remove-lifecycle stale
> 
> @mansikulkarni96 please address the comments and lets close this out.

@aravindhp thanks for reviewing, this one fell off my radar. Updated PTAL when you get a chance.

2022-08-15 23:17 UTC, aravindhp requested changes
Thanks for updating the PR, @mansikulkarni96. Just a few minor comments.

2022-08-15 23:17 UTC, aravindhp commented on enhancements/windows-containers/windows-machine-config-operator.md
> +* Install and configure the containerd container runtime on the Windows instances WMCO version 6.0.0 onwards.
`Install and configure the containerd container runtime on Windows instances managed by WMCO version 6.0.0 onwards.` 
And lets stick to 80 column width as I think that is the standard this doc is following.

2022-08-15 23:17 UTC, aravindhp commented on enhancements/windows-containers/windows-machine-config-operator.md
> +to bring up Windows worker nodes, they will create a [MachineSet](https://github.com/openshift/machine-api-operator/blob/master/config/machineset.yaml) where they reference a Windows OS image which h
`they will create MachineSets...`

Please format with 80 columns. It is okay for a the URL to go beyond 80 columns.

2022-08-15 23:17 UTC, aravindhp commented on enhancements/windows-containers/windows-machine-config-operator.md
> +Enabling the Docker container runtime is not required for bringing up Windows worker nodes WMCO 6.0.0 onwards.
`...Windows worker nodes using WMCO 6.0.0 onwards.`

2022-08-15 23:49 UTC, aravindhp approved these changes
Thanks for doing this, @mansikulkarni96

2022-08-15 23:50 UTC, aravindhp commented
/uncc @ashcrow @jwforres

2022-08-15 23:50 UTC, aravindhp commented
/cc @openshift/openshift-team-windows-containers

2022-08-16 11:41 UTC, sebsoto commented
/lgtm

2022-08-16 11:46 UTC, merged