feat(hypershift): Priority class dynamic adjustment
openshift/enhancements pull request #1384
Opened 2023-04-20 22:02 UTC by a-dsouza

This is an enhancement document for the priority class issue: https://github.com/openshift/hypershift/issues/1041

2023-04-24 20:54 UTC, jewzaam requested changes

2023-04-24 20:54 UTC, jewzaam commented on enhancements/hypershift/priority-class/priority-class-dynamic-adjustment.md
> +HyperShift currently creates a static set of default priority classes. We propose to add support for dynamically adjusting priority classes for the underlying control plane workloads. This will help
Does this imply dynamic creation of priority class to accomidate arbitrarily large hosted clusters?

2023-05-30 21:56 UTC, csrwng commented
/remove-lifecycle rotten

2023-07-13 00:15 UTC, closed without merging

2023-07-14 13:22 UTC, dhellmann commented
(automated message) This pull request is closed with lifecycle/rotten. It does not appear to be linked to a valid Jira ticket. Should the PR be reopened, updated, and merged? If not, removing the lifecycle/rotten label will tell this bot to ignore it in the future.

2023-07-14 13:33 UTC, csrwng commented
@a-dsouza pls reopen this when we're ready to work on it