register the metrics port for the baremetal-operator
openshift/enhancements pull request #470
Opened 2020-09-10 19:43 UTC by dhellmann

This is the port number the MAO uses when configuring the
baremetal-operator in 4.6.

2020-09-10 19:43 UTC, dhellmann commented
/cc @hardys @russellb @stbenjam

2020-09-11 01:13 UTC, russellb requested changes

2020-09-11 01:13 UTC, russellb commented on enhancements/network/host-port-registry.md
> +| 60000 | baremetal-operator | kni || metrics |
```suggestion
| 60000 | baremetal-operator | kni || metrics, 4.6+, control plane only |
```

2020-09-11 19:00 UTC, dhellmann commented
The update as been squashed and this should be ready to merge.

2020-09-11 20:04 UTC, russellb approved these changes

2020-09-11 20:04 UTC, russellb commented
/lgtm

2020-09-11 20:07 UTC, merged